# Generated by Django 4.0.6 on 2024-03-01 10:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(default='', max_length=15)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(default='', max_length=30)),
                ('dueDate', models.DateField(default=datetime.date.today)),
                ('prio', models.CharField(default='', max_length=15)),
                ('column', models.CharField(default='', max_length=50)),
                ('assignedContacts', models.ManyToManyField(to='contacts.contact')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
