# Generated by Django 4.0.6 on 2024-02-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_freecolors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FreeColors',
            new_name='FreeColor',
        ),
    ]
