# Generated by Django 4.0.6 on 2024-02-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0004_rename_freecolors_freecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column_category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedContacts',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='dueDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='prio',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=15),
        ),
    ]
