# Generated by Django 4.0.6 on 2024-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_remove_task_column_category_remove_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.CharField(default='', max_length=30),
        ),
    ]
