# Generated by Django 4.0.6 on 2024-02-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0007_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdefcategory',
            old_name='color',
            new_name='colorCode',
        ),
        migrations.RenameField(
            model_name='userdefcategory',
            old_name='title',
            new_name='name',
        ),
    ]
