# Generated by Django 4.0.6 on 2024-02-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0009_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedContacts',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedContacts',
            field=models.ManyToManyField(to='scrumboard.contact'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(to='scrumboard.subtask'),
        ),
    ]
