# Generated by Django 4.0.6 on 2024-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0012_rename_description_subtask_subtaskname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='taskId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
