# Generated by Django 4.0.6 on 2024-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0013_subtask_taskid_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.CharField(default='', max_length=50),
        ),
    ]
