# Generated by Django 4.0.6 on 2024-02-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0017_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeColor',
        ),
    ]
