# Generated by Django 4.0.6 on 2024-03-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0021_delete_userdefcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedContacts',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
