# Generated by Django 4.0.6 on 2024-03-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0022_remove_task_assignedcontacts_remove_task_author'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='taskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
