# Generated by Django 4.0.6 on 2024-03-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0023_alter_subtask_taskid_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
